### ISSUE TITLE
_tkinter.TclError: couldn't recognize data in image file "resources/info.png"

### ISSUE THREAD

**Issue by thenetimp** [nimaid/LPHK#1]
I cloned this on my mac.  Python 3.6 in a virtual environment.  Installed the dependencies, and then ran the script as in the instructions and get this error trace.

Traceback (most recent call last):
  File "LPHK.py", line 56, in <module>
    main()
  File "LPHK.py", line 52, in main
    window.init(lp)
  File "/Users/jandrews/Projects/innovation-cmd/LPHK/window.py", line 26, in init
    make()
  File "/Users/jandrews/Projects/innovation-cmd/LPHK/window.py", line 335, in make
    app = Main_Window(root)
  File "/Users/jandrews/Projects/innovation-cmd/LPHK/window.py", line 33, in __init__
    self.info_image = tk.PhotoImage(file="resources/info.png").subsample(2, 2)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 3539, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 3495, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "resources/info.png"

**Comment by nimaid** [comment]
The image error was because the PNG files were greyscale, not RGBA. While tk.PhotoImage worked with them on my Linux/Windows computers, it seems to not work on some (like your Mac.) [This commit](https://github.com/nimaid/LPHK/commit/8031e1e11cc7d84d1ea38431264a6790febdc706) replaces the tk.PhotoImage with a Pillow equivalent. In addition, the icons are now in a more common RGBA format.

[As for your TC64, it has a compatibility mode to emulate a Launchpad S](https://github.com/FMMT666/launchpad.py/issues/4). [If you enter this mode, your device will be compatible with the underlying library I use to talk with it](https://github.com/FMMT666/launchpad.py/issues/16). However, I still need to get my hands on an older Launchpad to add the color palettes so it will work with LPHK. That is on the to-do list, so stay tuned! (Or lend me your TC64 to develop with. :P)

I would very much appreciate you running the new version to verify the image error is resolved, as I can't recreate the error myself. Again, it won't connect to your device, but if the error message correctly shows the ! icon, I can close this issue.

**Comment by thenetimp** [comment]
After adding the new dependency with pip I was able start the application.  Since my other issue is unrelated to the original, I'll close this as it's fixed.
