### ISSUE TITLE
Option to disable sending out lights

### ISSUE THREAD

**Issue by JustLeader69420** [nimaid/LPHK#85]
So I wanted to use LPHK for macros, and Apollo for beautiful lights, LPHK overwrites the lights as soon as I press a macro tho... Could you please make an option to not send out lights or something? Would love to use both programs together.

**Comment by duncte123** [comment]
No sorry, if you want this functionality you should mod LPHK yourself or find a different program

**Comment by SimplyMerlin** [comment]
I'm quite confused by this. Why should I and anyone else have to find a different program or mod LPHK ourselves just to be able to disable light output? This seems more like a QoL change then anything. It's not demanding at all to just be able to disable light feedback.

Are you just shutting this idea off cause it would allow people to use Apollo Studio as a light engine instead of the built in engine? Cause that seems quite strange. This software is quite limited with lights after all.

**Comment by mat1jaczyyy** [comment]
> 
> No sorry, if you want this functionality you should mod LPHK yourself or find a different program

care to elaborate why? can be called something like 'work in the background' or 'ghost mode'... can get very creative with this

**Comment by duncte123** [comment]
> I'm quite confused by this. Why should I and anyone else have to find a different program or mod LPHK ourselves just to be able to disable light output? This seems more like a QoL change then anything. It's not demanding at all to just be able to disable light feedback.
> 
> Are you just shutting this idea off cause it would allow people to use Apollo Studio as a light engine instead of the built in engine? Cause that seems quite strange. This software is quite limited with lights after all.

I'm shutting this idea off because it's too high risk of breaking LPHK, the lights are controlled in a stupid manner and I'm scared that it would cause a full rewrite of the program before it would even remotely allow a feature like this.

The idea sounds quite simple but it's not simple to implement, especially since the light system in lphk should just get a rewrite and not be integrated into the command system anymore

**Comment by mat1jaczyyy** [comment]
if you're invoking the midi output command directly everywhere, wrap it into a func with an if statement. no amount of bad coding should prevent you from doing this easily
